import { useMemo } from "react";
import { Panel } from "./Panel";
import { useDataset } from "@/lib/dataset-store";
import { describe, numericValues } from "@/lib/data/stats";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

export function MemoPanel() {
  const { dataset } = useDataset();
  const md = useMemo(() => {
    if (!dataset) return "_Load a dataset to auto-generate documentation._";
    const lines: string[] = [];
    lines.push(`# Executive Engineering Memo`);
    lines.push(`**Dataset:** \`${dataset.name}\``);
    lines.push(`**Shape:** ${dataset.rows.length.toLocaleString()} rows × ${dataset.columns.length} columns`);
    lines.push(`\n## Schema discovered`);
    lines.push("| Column | Type | Notes |");
    lines.push("|---|---|---|");
    for (const c of dataset.columns) {
      const nullCount = dataset.rows.filter((r) => r[c.name] === null).length;
      lines.push(`| ${c.name} | ${c.type} | ${nullCount} nulls (${((nullCount/dataset.rows.length)*100).toFixed(1)}%) |`);
    }
    lines.push(`\n## Statistical anomalies`);
    for (const c of dataset.columns) {
      if (c.type !== "numeric") continue;
      const s = describe(numericValues(dataset.rows, c.name));
      const flags: string[] = [];
      if (Math.abs(s.skew) > 1) flags.push(`heavily skewed (${s.skew.toFixed(2)})`);
      if (Math.abs(s.kurtosis) > 3) flags.push(`heavy-tailed (kurt ${s.kurtosis.toFixed(2)})`);
      if (s.cv > 50) flags.push(`high volatility (CV ${s.cv.toFixed(1)}%)`);
      if (flags.length) lines.push(`- **${c.name}**: ${flags.join(", ")}`);
    }
    lines.push(`\n## Missing-value handling`);
    lines.push(`- Strategy: coerced non-numerics to \`null\` in numeric columns; preserved categorical strings as-is.`);
    lines.push(`\n## Generated by`);
    lines.push(`Neo Analytics v1.0 · client-side engine · zero server round-trips`);
    return lines.join("\n");
  }, [dataset]);

  return (
    <Panel title="Auto-Generated Executive Memo" subtitle="README-style engineering documentation">
      <article className="prose prose-sm prose-invert max-w-none text-sm scrollbar-thin overflow-auto max-h-[420px]">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>{md}</ReactMarkdown>
      </article>
    </Panel>
  );
}